apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-credential-helper
  namespace: ecr-credentials
spec:
  schedule: "0 */6 * * *"  # Run every 6 hours
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default
          containers:
          - name: ecr-credential-helper
            image: amazon/aws-cli:latest
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop: ["ALL"]
              seccompProfile:
                type: RuntimeDefault
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: ecr-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ecr-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: ecr-credentials
                  key: AWS_REGION
            command:
            - /bin/sh
            - -c
            - |
              # Get the ECR token
              TOKEN=$(aws ecr get-login-password)
              
              # Get AWS account ID
              ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
              
              # Create a Docker config.json with ECR credentials
              echo "{\"auths\": {\"${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com\": {\"auth\": \"$(echo -n AWS:${TOKEN} | base64)\"}}}" > /tmp/config.json
              
              # Create or update the Docker registry secret in all namespaces
              kubectl create secret generic ecr-docker-registry --from-file=.dockerconfigjson=/tmp/config.json --type=kubernetes.io/dockerconfigjson -o yaml --dry-run=client | kubectl apply -f -
              
              # Also create the secret in the default namespace
              kubectl create secret generic ecr-docker-registry --namespace=default --from-file=.dockerconfigjson=/tmp/config.json --type=kubernetes.io/dockerconfigjson -o yaml --dry-run=client | kubectl apply -f -
              
              echo "ECR credentials updated successfully"
          restartPolicy: OnFailure
