name: Backend CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'hobbyhelper-backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Test
        run: |
          cd hobbyhelper-backend
          go test ./...
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/hobbyhelper-backend
          tags: |
            type=sha,format=short
            type=ref,event=branch
            latest

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./hobbyhelper-backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Checkout flux repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/papyri
          ref: main
          token: ${{ secrets.FLUX_PAT }}
          path: papyri
          
      - name: Update image tag in Flux repository
        run: |
          cd papyri
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/hobbyhelper-backend:sha-$SHORT_SHA"
          
          # Update the image tag in the backend.yaml file
          sed -i "s|image: ghcr.io/${{ github.repository_owner }}/hobbyhelper-backend:.*|image: $IMAGE_TAG|" clusters/turing/apps/hobbyhelper/backend.yaml
          
          # Configure Git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Commit and push changes
          git add clusters/turing/apps/hobbyhelper/backend.yaml
          git commit -m "Update backend image to $SHORT_SHA"
          git push
